# Generated by Django 5.0.7 on 2024-12-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_loanapplicationforms_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanApplication',
            new_name='LoanApplications',
        ),
    ]
