# Generated by Django 5.0.7 on 2024-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
